apiVersion: apps/v1
kind: Deployment
metadata:
  name: valaxy-regapp # "valaxy" and "regapp" are intentional names
  labels:
    app: regapp # "regapp" is an intentional name

spec:
  replicas: 2
  selector:
    matchLabels:
      app: regapp

  template:
    metadata:
      labels:
        app: regapp
    spec:
      automountServiceAccountToken: false
      containers:
        - name: regapp
          image: valaxy/regapp:v1.0.0 # Specify a version tag
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "128Mi" # Specify memory request
              cpu: "250m"     # Specify CPU request
              ephemeral-storage: "1Gi" # Specify storage request
            limits:
              memory: "256Mi" # Specify memory limit
              cpu: "500m"     # Specify CPU limit
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1